# Generated by Django 2.0.4 on 2018-05-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=30)),
                ('crop_img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('subdescription', models.CharField(max_length=20)),
                ('crop_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizerapp.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='weather_condition_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizerapp.Weather'),
        ),
    ]
