# Generated by Django 2.0.4 on 2018-04-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop',
            new_name='crop_text',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='weather',
            new_name='weather_text',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='fertilizer',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='fertilizer',
        ),
    ]
