# Generated by Django 2.0.4 on 2018-04-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizerapp', '0002_auto_20180426_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
